const github = require("@actions/github");
const core = require("@actions/core");

async function createFixPR(token, analysis, context) {
  if (!analysis.codeFix || !analysis.codeFix.file || !analysis.codeFix.content) {
    core.info("No code fix available for auto-PR");
    return null;
  }

  const octokit = github.getOctokit(token);
  const { owner, repo } = context.repo;
  const baseBranch = context.ref.replace("refs/heads/", "");
  const fixBranch = `logytics-fix/${context.sha.substring(0, 7)}`;

  try {
    // Get the base branch ref
    const { data: baseRef } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${baseBranch}`,
    });

    // Create new branch
    core.info(`Creating branch: ${fixBranch}`);
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${fixBranch}`,
      sha: baseRef.object.sha,
    });

    // Get current file content (if exists)
    let currentSha = null;
    try {
      const { data: currentFile } = await octokit.rest.repos.getContent({
        owner,
        repo,
        path: analysis.codeFix.file,
        ref: fixBranch,
      });
      currentSha = currentFile.sha;
    } catch (e) {
      // File doesn't exist, that's ok
    }

    // Create or update file
    core.info(`Updating file: ${analysis.codeFix.file}`);
    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: analysis.codeFix.file,
      message: `fix: ${analysis.rootCause}\n\nAuto-generated by Logytics`,
      content: Buffer.from(analysis.codeFix.content).toString("base64"),
      branch: fixBranch,
      sha: currentSha,
    });

    // Create PR
    core.info("Creating pull request...");
    const { data: pr } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: `🔧 Fix: ${analysis.rootCause.substring(0, 60)}`,
      body: `## Auto-generated Fix by Logytics

### Root Cause
${analysis.rootCause}

### Explanation
${analysis.explanation || "See the suggested fix below."}

### Changes Made
- Modified \`${analysis.codeFix.file}\`

### Confidence
${analysis.confidence >= 80 ? "🟢" : analysis.confidence >= 50 ? "🟡" : "🔴"} **${analysis.confidence}%**

---
⚠️ **Please review this PR carefully before merging.**

*Generated by [Logytics](https://logytics.dev)*`,
      head: fixBranch,
      base: baseBranch,
    });

    core.info(`PR created: ${pr.html_url}`);
    return pr.html_url;
  } catch (error) {
    core.warning(`Failed to create fix PR: ${error.message}`);
    return null;
  }
}

module.exports = { createFixPR };
